build: disable `linux_ppc64le` target
Build fails with

> error: linking with `$BUILD_PREFIX/bin/powerpc64le-conda-linux-gnu-cc` failed: exit status: 1

when cross-compiling from `linux_64` (linking `libring` fails).

Native (emulated) builds are not an option anymore since there's no
`nodejs` for `linux_ppc64le` to build the web UI assets.